const { handler } = require('./dist/index');

handler({
  resource: '/namepicker',
  path: '/v1/namepicker',
  httpMethod: 'GET',
  headers: {
    accept:
      'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7,ja;q=0.6',
    Host: 'api-dev.damgle.com',
    'sec-ch-ua': '" Not A;Brand";v="99", "Chromium";v="102", "Google Chrome";v="102"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"macOS"',
    'sec-fetch-dest': 'document',
    'sec-fetch-mode': 'navigate',
    'sec-fetch-site': 'none',
    'sec-fetch-user': '?1',
    'upgrade-insecure-requests': '1',
    'User-Agent':
      'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36',
    'X-Amzn-Trace-Id': 'Root=1-62aef801-4446a54035186b0d1579159e',
    'X-Forwarded-For': '61.73.11.117',
    'X-Forwarded-Port': '443',
    'X-Forwarded-Proto': 'https',
  },
  multiValueHeaders: {
    accept: [
      'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
    ],
    'accept-encoding': ['gzip, deflate, br'],
    'accept-language': ['ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7,ja;q=0.6'],
    Host: ['api-dev.damgle.com'],
    'sec-ch-ua': ['" Not A;Brand";v="99", "Chromium";v="102", "Google Chrome";v="102"'],
    'sec-ch-ua-mobile': ['?0'],
    'sec-ch-ua-platform': ['"macOS"'],
    'sec-fetch-dest': ['document'],
    'sec-fetch-mode': ['navigate'],
    'sec-fetch-site': ['none'],
    'sec-fetch-user': ['?1'],
    'upgrade-insecure-requests': ['1'],
    'User-Agent': [
      'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36',
    ],
    'X-Amzn-Trace-Id': ['Root=1-62aef801-4446a54035186b0d1579159e'],
    'X-Forwarded-For': ['61.73.11.117'],
    'X-Forwarded-Port': ['443'],
    'X-Forwarded-Proto': ['https'],
  },
  queryStringParameters: null,
  multiValueQueryStringParameters: null,
  pathParameters: null,
  stageVariables: null,
  requestContext: {
    resourceId: 'hysx39',
    resourcePath: '/namepicker',
    httpMethod: 'GET',
    extendedRequestId: 'T9uwNGgpoE0Ffaw=',
    requestTime: '19/Jun/2022:10:18:41 +0000',
    path: '/v1/namepicker',
    accountId: '466443433231',
    protocol: 'HTTP/1.1',
    stage: 'v1',
    domainPrefix: 'api-dev',
    requestTimeEpoch: 1655633921130,
    requestId: '2de08eee-0070-47ca-b012-a61815fa045f',
    identity: {
      cognitoIdentityPoolId: null,
      accountId: null,
      cognitoIdentityId: null,
      caller: null,
      sourceIp: '61.73.11.117',
      principalOrgId: null,
      accessKey: null,
      cognitoAuthenticationType: null,
      cognitoAuthenticationProvider: null,
      userArn: null,
      userAgent:
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36',
      user: null,
    },
    domainName: 'api-dev.damgle.com',
    apiId: '7qo4pkkac1',
  },
  body: null,
  isBase64Encoded: false,
}).then(console.log);
